import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hcl.sb.amp.vg/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('partner1');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Lovish@1995');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.goto('https://hcl.sb.amp.vg/#dashboard/partneruser');
  await page.getByRole('button', { name: 'Register Opportunity' }).click();
  await page.getByText('I agree', { exact: true }).click();
  await page.locator('a').filter({ hasText: 'Search by End Customer' }).click();
  await page.locator('#select2-drop').getByRole('textbox').fill('mm');
  await page.getByText('Acme Systems Sync MM, Inc. (HCL47439) (HCL47439)').click();
  await page.getByText('Back Opportunity Details').click();
  await page.getByText('Accept').click();
  await page.getByPlaceholder('Email').click();
  await page.getByPlaceholder('Email').fill('sunil.bind01@maildrop.cc');
  await page.getByPlaceholder('Name', { exact: true }).click();
  await page.getByPlaceholder('Name', { exact: true }).fill('Sunil Bind');
  await page.getByPlaceholder('Job Title').click();
  await page.getByPlaceholder('Job Title').fill('QA');
  await page.getByPlaceholder('Telephone').click();
  await page.getByPlaceholder('Telephone').fill('7845875489');
  await page.locator('#wizardNext').click();
  await page.getByPlaceholder('Opportunity Name').click();
  await page.getByPlaceholder('Opportunity Name').click();
  await page.getByPlaceholder('Opportunity Name').fill('Test opp Confirm');
  await page.locator('#s2id_select-2 a').filter({ hasText: 'Select' }).click();
  await page.locator('#select2-drop').getByText('DF Test Campaign').click();
  await page.locator('#s2id_select-3 a').filter({ hasText: 'Select' }).click();
  await page.locator('#select2-drop').getByText('Distributor to Reseller').click();
  await page.locator('#s2id_select-4 a').filter({ hasText: 'Select' }).click();
  await page.locator('#select2-drop').getByRole('textbox').fill('48454');
  await page.locator('#select2-drop').getByText('test (HCL48454)').click();
  await page.getByPlaceholder('Estimated Closed Date').click();
  await page.getByRole('cell', { name: '31' }).nth(1).click();
  await page.locator('a').filter({ hasText: 'Select' }).click();
  await page.locator('#select2-drop').getByText('SaaS', { exact: true }).click();
  await page.locator('#wizardNext').click();
  await page.locator('.select2-choice').click();
  await page.locator('#select2-drop').getByText('HCL Volt MX').click();
  await page.locator('#description').click();
  await page.locator('#description').fill('Test Comments');
  await page.getByPlaceholder('<CURRENCY>').click();
  await page.getByPlaceholder('<CURRENCY>').fill('25687');
  await page.locator('#modalActionButtons a').filter({ hasText: 'Finish' }).click();
});